window.taskReferenceSeed = {
  "headers": [
    "Category",
    "Work to be done",
    "Priority",
    "Responsible",
    "Assistant",
    "Allocation date",
    "Timeline",
    "Status",
    "Completion date",
    "Achv. day( Early/ Late)",
    "Rating ( Quality, execution, timeline))"
  ],
  "projects": [
    {
      "kind": "Open",
      "category": "HR/ADMIN",
      "work": "Leave application, approval process, format and training",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "24-06-2026",
      "timeline": "24-06-2026",
      "status": "9/10",
      "completionDate": "24-06-2026",
      "achievementDay": "0",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Wall poster for area identification to install in part B",
      "priority": "",
      "responsible": "SD",
      "assistant": "MM",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "10/10",
      "completionDate": "24-06-2026",
      "achievementDay": "1",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Jumbo bags to place on rack",
      "priority": "",
      "responsible": "MM",
      "assistant": "SD",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Counting of available different empty Paper sacks and Jumbo bags",
      "priority": "",
      "responsible": "RP",
      "assistant": "KP",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "2/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Missing PSD of available raw materials stored for long time",
      "priority": "",
      "responsible": "RP",
      "assistant": "SD",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "PSD sheet pending backlog to fill up (Hardcopy) from Notebook to printed sheets.",
      "priority": "",
      "responsible": "RP",
      "assistant": "SD",
      "allocationDate": "16-06-2026",
      "timeline": "01-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Filing of different Hardcopies to implement (GRN, Requisitions etc.)",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "3/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Labelling of stacked material in the flag",
      "priority": "",
      "responsible": "SD",
      "assistant": "SM/KP",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "PSD of produced raw material everyday before stacking in both of the shift during blending downtime.",
      "priority": "",
      "responsible": "RP",
      "assistant": "SM",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "4/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Segregation and proper stacking of existing different materials with proper marking.",
      "priority": "",
      "responsible": "SD",
      "assistant": "SM",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "2/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Storage area defining work as per new layout (Specified area for like, TNC 14/16, TNC 10/20 etc.)",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "10-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Implement the new Layout",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Roads marking with yellow paint as per new layout.",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Labour quarter 2-3 rooms (Tin)",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "MM",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "1/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "New balloon bags for different machines (Good quality)",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "PJ",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Housekeeping of Lab & Office",
      "priority": "",
      "responsible": "RP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "3/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Store",
      "work": "Arrangement of Storeroom with proper inventory and tracking system",
      "priority": "",
      "responsible": "KP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "1/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Few CCTV repositioning",
      "priority": "",
      "responsible": "SD",
      "assistant": "PJ",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "10/10",
      "completionDate": "18-06-2026",
      "achievementDay": "7",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Get the cupboard with attached hanger for Lab to store PPE",
      "priority": "",
      "responsible": "MM",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Keep ready all the variants of processed raw material required for each and every EMC product for minimum of 1 Container.",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "2/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Production chain setup for each and every material required for different EMC products.",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Cleaning of Part B",
      "priority": "",
      "responsible": "RP",
      "assistant": "MM",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Jumbo to Paper sacks conversion (ACF/ACUF)",
      "priority": "",
      "responsible": "KP",
      "assistant": "SD",
      "allocationDate": "16-06-2026",
      "timeline": "05-07-2026",
      "status": "4/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Fix the dust leakage in Office/ Lab/ Store & Height increase of the Part A to Part B connecting door.",
      "priority": "",
      "responsible": "MM",
      "assistant": "PJ",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Pallet stacker & Forklift timely preventive maintenance. Proper cleaning every day of the chain area.",
      "priority": "",
      "responsible": "PP",
      "assistant": "KP",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Paint work of newly manufactured equipment",
      "priority": "",
      "responsible": "MM",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "29-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "HSE",
      "work": "Safety gear hanging hooks for visitors near main entrance",
      "priority": "",
      "responsible": "MM",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Emergency contacts to be displayed in multiple area of Factory",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Available screens (MTR2, MTR3, VS, RS) Micron measurement and marking on the specific screen along with total data base of available screens.",
      "priority": "",
      "responsible": "KP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "10-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "With the extra labour fold all the available paper bags for hassle free emergency blending in future.",
      "priority": "",
      "responsible": "RP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "MLP grit segregation as following 8/10, 10/14, 14/16, 16/18, <18 (Assign a separate machine for MLP processing)",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Identify the wet Paper sacks of ACUF/ACF/ACM in the wall side, change the bags",
      "priority": "",
      "responsible": "KP",
      "assistant": "MM",
      "allocationDate": "16-06-2026",
      "timeline": "20-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "Create strict rules for proper stacking of material, No tolerance for wrong placement and stacking. (SOP)",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "10/10",
      "completionDate": "18-06-2026",
      "achievementDay": "7",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Purchase",
      "work": "Order one more Industrial vacuum cleaner (If approved)",
      "priority": "",
      "responsible": "PJ",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "House keeping",
      "work": "Cleaning, house keeping supervision should be stricter, it’s not about cleaning the available floor area, if something unnecessary laying on floor need to be cleaned, there are lots of example that requires serious attention.",
      "priority": "",
      "responsible": "RP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "3/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "HSE",
      "work": "Fire safety alarms and rest necessary things to implement along with emergency exit.",
      "priority": "",
      "responsible": "PJ",
      "assistant": "SD",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-20206",
      "status": "4/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "HSE",
      "work": "Fire drill",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "05-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "ISO",
      "work": "Sit with both the Audit report, and prepare bullet points to complete the pending documents",
      "priority": "",
      "responsible": "SD",
      "assistant": "KP/PJ",
      "allocationDate": "16-06-2026",
      "timeline": "29-06-2026",
      "status": "2/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "ISO",
      "work": "Formatting of SOP’s",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "29-06-2026",
      "status": "6/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "ISO",
      "work": "Pending formats/ templates",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "29-06-2026",
      "status": "6/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Logistic",
      "work": "New rack tracking manual",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "22-06-2026",
      "status": "10/10",
      "completionDate": "17-06-2026",
      "achievementDay": "5",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Incoming material vs Produced material Stats quarterly = Balance stock",
      "priority": "",
      "responsible": "SD",
      "assistant": "PJ",
      "allocationDate": "16-06-2026",
      "timeline": "10-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Create detailed project plan for Improvements and list pending works",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "18-06-2026",
      "status": "10/10",
      "completionDate": "17-06-2026",
      "achievementDay": "1",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Write the summarized Activity log on daily basis.",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Machinery Folder requires serious attention, fix the wrong things",
      "priority": "",
      "responsible": "KP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "ISO",
      "work": "All The ISO related documents must be in order, easy to access",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "ISO",
      "work": "Create a SOP for post blending Jumbo tracking along with Paper sacks",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Reactivate the daily production and stock template",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Work on Combined stock and formulation, stock will directly reflect in the formulation tab of each product",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Documentation",
      "work": "Create the presentation of factory development over time",
      "priority": "",
      "responsible": "SD",
      "assistant": "PJ/SN",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Install wire mesh/ Perforated sheet and check production rate with PSD of the different outputs (1.5mm, 2mm, 2.5mm, 3mm)",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Trial run and check for the different issues and its prevention",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Frequent tripping Issue and, air lock damage (Root cause) solution, Extra balloon slot to install",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "3/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Root cause analysis of Air lock motor damage frequently and provide solution",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "3/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Dusting issue during operation and  set grinding parameter (Regulator system) implementation",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "10-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Foam setup as per SM instruction to implement in each screen",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Vibration adjustment for smooth material flow.",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Modified top deck screen modification to get fit in any of the deck, similar any of the existing screen should fit in top deck.",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "15-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Increase vibration efficiency for better screening",
      "priority": "",
      "responsible": "PP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Leakage problem (Oversized contamination) to fix ASAP",
      "priority": "",
      "responsible": "PP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Hopper design to change for smooth feeding & Support stand",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Whole body of the machine requires modification, as damages are visible from different area, bottom plate, conveyor leakage, side body crack etc.",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "4/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Entire screen installation process to make it user friendly and less time consuming. Find a way out to avoid frequent screen damage.",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Hopper body is cracked, requires serious attention. Leakage from the inner shaft need to be cured to minimize dust",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "CNC conveyor to repair ASAP, as it is laying here for 3-4 months",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Metal screen frame to install, and prepare at least  4 Pairs for different screens",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "10-07-2026",
      "status": "2.5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Outlet gate modification along with MTR3/MTR2 to prevent dust",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "30-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "In both of the blender, new modified vibratory screen system to implement.",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "5/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "In both of the blender discharge gate leakage issue to solve to prevent dusting",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "The motor is damaged in the first run, fix it ASAP",
      "priority": "",
      "responsible": "PP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "5/10",
      "completionDate": "20-06-2026",
      "achievementDay": "5",
      "rating": "7/10",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Get the accurate production rate of different machinery, and get it documented, (Material selection is crucial), Keep feeding rate VS retention VS output PSD in mind while measuring the production rate.",
      "priority": "",
      "responsible": "PP",
      "assistant": "KP",
      "allocationDate": "16-06-2026",
      "timeline": "30-07-2026",
      "status": "4/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Different adjustment and screen setup for different output manual for supervisors for easy screen selection or setup",
      "priority": "",
      "responsible": "SD",
      "assistant": "PP",
      "allocationDate": "16-06-2026",
      "timeline": "20-07-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Install it with immediate effect  ( Mechanical Sieve shaker, Lab)",
      "priority": "",
      "responsible": "KP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "17-06-2026",
      "status": "10/10",
      "completionDate": "20-06-2026",
      "achievementDay": "-3",
      "rating": "4/10",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Granden expansion in the main enterance",
      "priority": "",
      "responsible": "MM",
      "assistant": "DP",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "3/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Implement reverse forward mechanism in both Ribbon Blender",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "16-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Install handle in the RS2 frames for easy pull out from machine.",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "17-06-2026",
      "timeline": "18-06-2026",
      "status": "0/10",
      "completionDate": "19-06-2026",
      "achievementDay": "-1",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Water ingress issue identification and repair",
      "priority": "",
      "responsible": "PJ",
      "assistant": "SD/KP/PP",
      "allocationDate": "",
      "timeline": "",
      "status": "",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Damged shutter to replace",
      "priority": "",
      "responsible": "PJ",
      "assistant": "",
      "allocationDate": "25-06-2026",
      "timeline": "",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Cleaning",
      "work": "Contact external cleaner and give them contact for higher area cleaning inside factory.",
      "priority": "",
      "responsible": "PJ",
      "assistant": "",
      "allocationDate": "25-06-2026",
      "timeline": "",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Production",
      "work": "Implement the production plan created by SD",
      "priority": "",
      "responsible": "PP",
      "assistant": "KP",
      "allocationDate": "18-06-2026",
      "timeline": "22-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Implement hopper cover for every machinery",
      "priority": "",
      "responsible": "Mukul",
      "assistant": "PP",
      "allocationDate": "19-06-2026",
      "timeline": "15-07-2026",
      "status": "10/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Machinery",
      "work": "Install different screens ( 2#, 4#, 5#, 8#, 14#, 40# in both of the blender Hopper)",
      "priority": "",
      "responsible": "KP",
      "assistant": "Mukul",
      "allocationDate": "05-06-2026",
      "timeline": "30-06-2026",
      "status": "2/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "General",
      "work": "Get the industrial custom magnet for blender Hopper ( 2 NOS)",
      "priority": "",
      "responsible": "PP",
      "assistant": "PJ",
      "allocationDate": "01-06-2026",
      "timeline": "30-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Preventive maintenance, Consumption data sheet fill up",
      "priority": "",
      "responsible": "KP",
      "assistant": "PP",
      "allocationDate": "10-06-2026",
      "timeline": "25-06-2026",
      "status": "2/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "CFS 1/2 conveyor leakage to fix",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "19-06-2026",
      "timeline": "22-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "Maintenance",
      "work": "Ribbon Blender 2 : Possible ribbon damage to fix.",
      "priority": "",
      "responsible": "PP",
      "assistant": "MM",
      "allocationDate": "19-06-2026",
      "timeline": "20-06-2026",
      "status": "0/10",
      "completionDate": "",
      "achievementDay": "",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "HSE",
      "work": "Emrgency Contact list",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "9/10",
      "completionDate": "19-06-2026",
      "achievementDay": "1",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Open",
      "category": "HR",
      "work": "Induction training for new employee/ Intern to implement",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "20-06-2026",
      "status": "10/10",
      "completionDate": "18-06-2026",
      "achievementDay": "2",
      "rating": "",
      "remarks": ""
    }
  ],
  "completed": [
    {
      "kind": "Completed",
      "category": "HR/ADMIN",
      "work": "Leave application, approval process, format and training",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "24-06-2026",
      "timeline": "24-06-2026",
      "status": "9/10",
      "completionDate": "24-06-2026",
      "achievementDay": "0",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "General",
      "work": "Wall poster for area identification to install in part B",
      "priority": "",
      "responsible": "SD",
      "assistant": "MM",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "10/10",
      "completionDate": "24-06-2026",
      "achievementDay": "1",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "General",
      "work": "Few CCTV repositioning",
      "priority": "",
      "responsible": "SD",
      "assistant": "PJ",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "10/10",
      "completionDate": "18-06-2026",
      "achievementDay": "7",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "Logistic",
      "work": "Create strict rules for proper stacking of material, No tolerance for wrong placement and stacking. (SOP)",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "10/10",
      "completionDate": "18-06-2026",
      "achievementDay": "7",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "Logistic",
      "work": "New rack tracking manual",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "22-06-2026",
      "status": "10/10",
      "completionDate": "17-06-2026",
      "achievementDay": "5",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "Documentation",
      "work": "Create detailed project plan for Improvements and list pending works",
      "priority": "",
      "responsible": "SD",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "18-06-2026",
      "status": "10/10",
      "completionDate": "17-06-2026",
      "achievementDay": "1",
      "rating": "",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "Maintenance",
      "work": "The motor is damaged in the first run, fix it ASAP",
      "priority": "",
      "responsible": "PP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "25-06-2026",
      "status": "5/10",
      "completionDate": "20-06-2026",
      "achievementDay": "5",
      "rating": "7/10",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "Machinery",
      "work": "Install it with immediate effect  ( Mechanical Sieve shaker, Lab)",
      "priority": "",
      "responsible": "KP",
      "assistant": "",
      "allocationDate": "16-06-2026",
      "timeline": "17-06-2026",
      "status": "10/10",
      "completionDate": "20-06-2026",
      "achievementDay": "-3",
      "rating": "4/10",
      "remarks": ""
    },
    {
      "kind": "Completed",
      "category": "Machinery",
      "work": "Install handle in the RS2 frames for easy pull out from machine.",
      "priority": "",
      "responsible": "PP",
      "assistant": "Mukul",
      "allocationDate": "17-06-2026",
      "timeline": "18-06-2026",
      "status": "0/10",
      "completionDate": "19-06-2026",
      "achievementDay": "-1",
      "rating": "",
      "remarks": ""
    }
  ],
  "performanceHeaders": [
    "Person",
    "Total Allotted",
    "Completed Tasks",
    "Before Time",
    "On Time",
    "Timeline Failed",
    "Open Tasks"
  ],
  "performance": [
    {
      "Person": "SD",
      "Total Allotted": "30",
      "Completed Tasks": "8",
      "Before Time": "7",
      "On Time": "1",
      "Timeline Failed": "",
      "Open Tasks": "22"
    },
    {
      "Person": "PP",
      "Total Allotted": "23",
      "Completed Tasks": "2",
      "Before Time": "1",
      "On Time": "",
      "Timeline Failed": "1",
      "Open Tasks": "21"
    },
    {
      "Person": "PJ",
      "Total Allotted": "5",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": "5"
    },
    {
      "Person": "KP",
      "Total Allotted": "8",
      "Completed Tasks": "1",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "1",
      "Open Tasks": "7"
    },
    {
      "Person": "RP",
      "Total Allotted": "8",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": "8"
    },
    {
      "Person": "MUKUL",
      "Total Allotted": "8",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": "8"
    },
    {
      "Person": "MM",
      "Total Allotted": "6",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": "6"
    },
    {
      "Person": "DP",
      "Total Allotted": "",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": ""
    },
    {
      "Person": "SN",
      "Total Allotted": "",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": ""
    },
    {
      "Person": "SR",
      "Total Allotted": "",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": ""
    },
    {
      "Person": "SKM",
      "Total Allotted": "",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": ""
    },
    {
      "Person": "SM",
      "Total Allotted": "",
      "Completed Tasks": "",
      "Before Time": "",
      "On Time": "",
      "Timeline Failed": "",
      "Open Tasks": ""
    }
  ]
};
